# Generated by Django 4.1.6 on 2024-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteudo da frase')),
                ('creator', models.CharField(max_length=255, unique=True, verbose_name='Criador da frase')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags da Frase')),
            ],
        ),
    ]
