# Generated by Django 4.1.6 on 2024-03-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='creator',
            field=models.TextField(blank=True, null=True, verbose_name='Tags da Frase'),
        ),
    ]
