# Generated by Django 5.0.4 on 2024-04-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_movies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano do filme'),
        ),
    ]
