# Generated by Django 5.0.4 on 2024-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_movies_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data de filme'),
        ),
    ]
